import { NextRequest, NextResponse } from "next/server"
import { OK, secJson, type SourceReport } from "@/lib/sec"

/**
 * One executive-branch filer's public financial disclosures, from the Office
 * of Government Ethics' own index.
 *
 * Free, public-domain government data. No key, no login, no terms gate.
 *
 * THIS DATA MAY NEVER GO BEHIND THE PAYWALL
 * -----------------------------------------
 * 5 U.S.C. 13107(c)(1) makes it unlawful to use these reports for "any
 * commercial purpose, other than by news and communications media for
 * dissemination to the general public". Charging for access is the clearest
 * commercial use there is, so everything this route serves is free in the app
 * and stays free. The same rule already keeps the House disclosures out of the
 * plan (see /api/congress-filings and TrackerPersonView.alwaysFree, which is
 * `person.category == .politicians` and therefore already covers these three
 * officials). SEC Form 4 and Form 13F carry no such restriction, which is why
 * insiders and funds are gated and officials are not. Do not "unify" the
 * gating.
 *
 * WHAT THIS RETURNS, AND WHY IT STOPS THERE
 * -----------------------------------------
 * It returns the DOCUMENTS: what each one is, when OGE posted it, and a link to
 * the government's own PDF. It does NOT return the trades inside them.
 *
 * For the President that is not a preference, it is forced. Every one of his
 * 278-T transaction reports is published as a SCAN, and the OCR layer is
 * unusable in a different way on each filing: "purchase" comes out "lourchase",
 * dates come out "5/512026", and the oldest ones lose the Type column
 * altogether. A misread amount band is a number a reader might act on, so the
 * document gets linked and never parsed. Better OCR does not change this.
 *
 * The Cabinet secretaries' 278-Ts are generated by Integrity.gov and are clean,
 * typed text, so they could be parsed one day. That is a separate piece of work
 * with its own honesty rules, and nothing here should be read as a head start
 * on it.
 *
 * THE FEED, AND ITS TWO SURPRISES
 * -------------------------------
 * https://extapps2.oge.gov/201/Presiden.nsf/API.xsp/v2/rest hands back the WHOLE
 * index in one 7 MB body: 16,639 rows as of this writing and climbing, every
 * filer OGE holds, with no filter parameter of any kind. So this route pays for
 * all of it to answer about one person. Each row is
 * { agency, amended, docDate, level, name, title, type }, and `type` is a
 * fragment of HTML rather than a label. See parseType.
 *
 * 1. It fails intermittently, and the failure is upstream's, not ours. Some
 *    requests come back HTTP 400 carrying a Java
 *    ConcurrentModificationException out of
 *    gov.oge.apiv2.RestService.buildNomineeJSONOutput: the server is editing the
 *    list while it serialises it. Two failures in twelve spaced requests across
 *    two sessions, which is too few to put a rate on beyond "often enough to
 *    plan for". Nothing we send changes it and no header provokes it. Hence the
 *    retry and the stale fallback in indexRows.
 * 2. Its 7 MB body is too big for Next's data cache, which refuses entries over
 *    2 MB. `revalidate` below therefore does NOT save the download the way it
 *    does on every other route here, so the in-process memo does that job. The
 *    revalidate stays because it costs nothing and starts working the day either
 *    number moves.
 *
 * A NOTE ON THE STATUS FIELD
 * --------------------------
 * Every path returns HTTP 200 with a `filings` array, so a caller that reads
 * only the array cannot tell "OGE lists nothing for this person" from "we could
 * not read OGE". Those are different sentences and only the first is safe to
 * draw as an empty section. The status says which, and the client is required
 * to read it: TrackerPersonView.load treats "unavailable" as a page failure.
 */

export const revalidate = 21600

/**
 * A cold request downloads 7 MB and parses it. That is a couple of seconds on a
 * good day and the platform default leaves no room for a bad one.
 *
 * No other route in this app sets maxDuration, so this is a new setting rather
 * than a house idiom. If the deployment plan will not run a 30s function, lower
 * it and expect the occasional cold request to time out.
 */
export const maxDuration = 30

/** The whole index, in one response. There is no per-filer endpoint. */
const FEED = "https://extapps2.oge.gov/201/Presiden.nsf/API.xsp/v2/rest"

/**
 * Documents returned, newest first.
 *
 * This DOES truncate: nine filers in today's index are over it, the longest
 * being 151 documents. None of them is anyone the app tracks (the President
 * leads that group with 23), but the cap is real, so nothing downstream may
 * present `filings.length` as the number of documents OGE holds for a person.
 */
const MAX_FILINGS = 60

/**
 * HTML entities, decoded, the same way /api/fund-filings and /api/fund-holdings
 * decode them. Nothing in today's index carries one, but document labels are
 * free text typed by an agency ethics officer and one of them will eventually
 * contain an "&amp;". Commerce already publishes "Certificate of Divestiture
 * OGE-2025-070, 071, 072, 073, 074 & 075" with a bare ampersand, which is the
 * same string one escape away.
 */
function decodeEntities(s: string): string {
    return s
        .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
        .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&apos;/g, "'")
        // Ampersand last, so "&amp;lt;" does not become "<".
        .replace(/&amp;/g, "&")
}

/** The one anchor a `type` fragment carries, and the URL inside it. */
const ANCHOR = /<a\b[^>]*>([\s\S]*?)<\/a>/i
const HREF = /href\s*=\s*(?:'([^']*)'|"([^"]*)")/i

type OgeRow = {
    agency?: string
    amended?: string
    docDate?: string
    level?: string
    name?: string
    title?: string
    type?: string
}

type Parsed = {
    label: string
    documentUrl: string | null
    available: boolean
}

/**
 * What a `type` fragment actually says.
 *
 * It arrives as HTML in one of three shapes, and the difference is the whole
 * point of this function:
 *
 *   published    <a href='…/$FILE/Scott-Bessent-12.05.2025-278T.pdf'>278
 *                Transaction</a>
 *
 *   request only 278 Transaction (<a href='…/201%20Request?OpenForm&Filer=Patel'>
 *                Request this Document</a>)
 *                Conflict of Interest Waiver <a href='…contact-list'>(Contact
 *                agency to request)</a>
 *
 * The second and third differ in where the brackets sit: one wraps the anchor,
 * the other is inside it. Both are request rows, and the label rule below
 * handles them the same way.
 *
 * "$FILE" in the href is the discriminator and the only reliable one: all three
 * shapes are anchors, all point at a government host, and the request links
 * differ in wording between agencies. A request row is NOT a document. It is a
 * form a human fills in and waits on, and presenting it as something openable
 * would be a lie the reader only discovers after tapping.
 *
 * The label follows from the shape. When there is a document the anchor text IS
 * the label ("278 Transaction", "Annual (2026)", "Nominee 278"). When there is
 * not, the label is everything OUTSIDE the anchor, because the anchor holds the
 * request instruction and not the name of the document.
 *
 * Only the anchor is stripped, never every tag. Three rows in the index read
 * "Annual (<select one>)", where a filer left the placeholder in, and a blanket
 * tag strip silently turns that into "Annual ()", which hides that the
 * government's own record is incomplete. The app renders labels as plain text,
 * so a stray angle bracket shows as itself and misleads nobody.
 */
function parseType(raw: string): Parsed {
    const anchor = ANCHOR.exec(raw)
    const href = anchor ? HREF.exec(anchor[0]) : null
    const url = href ? decodeEntities(href[1] ?? href[2] ?? "") : ""
    const available = url.includes("$FILE")

    const inner = anchor ? anchor[1] : ""
    let label = available ? inner : raw.replace(ANCHOR, "")
    label = decodeEntities(label).replace(/\s+/g, " ").trim()
    // The empty brackets the removed anchor left behind. EVERY occurrence, not
    // just a trailing one: on 189 rows in today's index the request link sits
    // mid-string, so anchoring this to the end leaves "Nominee 278 ()" and
    // "New Entrant () (Pending Final OGE Disposition)" on screen. Note this
    // cannot touch "Annual (<select one>)" above, whose brackets are not empty.
    label = label.replace(/\s*\(\s*\)/g, "")
    // "(Amended 08/12/2025)" is the `amended` column repeated into the label.
    // It rides on isAmended and amendedAt instead, so the label stays the name
    // of the document.
    label = label.replace(/\s*\(Amended\s+[\d/.-]+\)\s*$/i, "")
    label = label.replace(/\s+/g, " ").trim()

    return {
        label: label || "Disclosure",
        documentUrl: available ? url : null,
        available,
    }
}

/**
 * Is this row this filer's?
 *
 * EXACT full-name equality, and nothing looser, ever. The index keys people as
 * "Surname, Forename" and the near-misses are not hypothetical:
 *
 *   "Trump, Donald J"  is the President; "Trump, Ivanka" also files.
 *   "Patel, Kashyap"   is the FBI Director; "Patel, Nutan" is the Ambassador to
 *                      Cabo Verde, and "Patelunas, Isabel M" is a third person
 *                      a prefix match would swallow whole.
 *   "Miller, Stephen"  files 4 documents; "Miller, Scott" files 42.
 *
 * Case and internal spacing are normalised, because those are formatting and a
 * re-key at OGE should not empty a page. Anything else is a different person.
 * Note also that "Trump, Donald J" carries no full stop after the initial.
 */
function normalizeName(name: string): string {
    return name.replace(/\s+/g, " ").trim().toLowerCase()
}

/**
 * Why the index isn't answering, in words about OGE rather than about the SEC.
 *
 * lib/sec.ts does the fetching and the classification, and that is exactly what
 * is wanted here: an index we couldn't download must not render as "this
 * official has disclosed nothing". Its stock reasons name the SEC though, and
 * this is a different agency, so the status is the library's and the sentence
 * is ours.
 */
function reportOfFeed(status: "no-data" | "unavailable"): SourceReport {
    return status === "no-data"
        ? { status, reason: "The OGE disclosure index has nothing at that address." }
        : { status, reason: "The OGE disclosure index couldn't be reached." }
}

/**
 * The last index this instance managed to read. See surprise 2 in the header:
 * the data cache will not hold a 7 MB body, so without this every reader pays
 * for the whole download again.
 *
 * Per-instance and lost on a cold start, which is the right trade: the worst
 * case is the fetch we would have made anyway. It does hold roughly 16,600
 * parsed rows in instance memory for as long as it is valid.
 */
let memo: { at: number; rows: OgeRow[] } | null = null

/** How long a memo may be served after the feed stops answering. */
const STALE_LIMIT_MS = 24 * 60 * 60 * 1000

/**
 * One row array, from the memo, the feed, or the memo again if the feed is
 * having one of its bad minutes.
 *
 * The retry is there because the upstream failure is a race inside OGE's own
 * serialiser rather than anything about our request, so the second attempt
 * usually lands. A failed attempt costs 3 KB, not 7 MB, because the 400 body is
 * a stack trace.
 *
 * Serving a stale index beats serving an error, and it is not a dishonest
 * answer: this index gains rows at most a few times a day, every row is dated,
 * and nothing on the page claims to be current as of this second. It is capped
 * anyway, so a feed that stays down eventually says so instead of quietly
 * showing last week.
 */
async function indexRows(): Promise<OgeRow[] | SourceReport> {
    const now = Date.now()
    if (memo && now - memo.at < revalidate * 1000) return memo.rows

    let last: SourceReport = reportOfFeed("unavailable")
    for (let attempt = 0; attempt < 2; attempt++) {
        const index = await secJson<OgeRow[] | { recordsTotal?: number; data?: unknown }>(
            FEED,
            revalidate
        )
        if (index.status !== "ok") {
            last = reportOfFeed(index.status)
            continue
        }

        // The error body is a 200-shaped object whose `data` is the stack trace
        // STRING, so the array check is load-bearing: without it the filter in
        // GET would throw on a value that is not an array. Today OGE sends that
        // body with a 400 and lib/sec.ts rejects it first, but the shape is one
        // header change away from arriving with a 200.
        const payload = index.data
        const wrapper = Array.isArray(payload) ? null : payload
        const list = Array.isArray(payload) ? payload : wrapper?.data
        const rows: OgeRow[] = Array.isArray(list) ? (list as OgeRow[]) : []

        // The feed states its own row count, so a body cut short mid-serialise
        // is caught here rather than memoised as the whole index. A short read
        // silently drops filings, which is the one failure this route must
        // never present as "nothing filed". A bare array states no count, and
        // then this compares rows.length with itself and passes.
        const claimed = wrapper?.recordsTotal ?? rows.length
        if (!rows.length || claimed !== rows.length) {
            last = {
                status: "unavailable",
                reason: "The OGE disclosure index came back incomplete.",
            }
            continue
        }

        memo = { at: now, rows }
        return rows
    }

    if (memo && now - memo.at < STALE_LIMIT_MS) return memo.rows
    return last
}

export async function GET(req: NextRequest) {
    const filer = (req.nextUrl.searchParams.get("filer") ?? "").trim()
    if (!filer) {
        return NextResponse.json({ error: 'Pass a filer, like "Bessent, Scott".' }, { status: 400 })
    }

    /** Keys stay put on every path, so a caller can always read `filings`. */
    const nothing = (report: SourceReport) =>
        NextResponse.json({
            filer,
            source: FEED,
            tradesIncluded: false,
            filings: [],
            ...report,
        })

    // The feed answers as { recordsTotal, recordsFiltered, data: [...] }, but a
    // bare array is the shape it was documented with, so indexRows accepts both
    // rather than betting the page on which wrapper is deployed the day someone
    // reads it.
    const rows = await indexRows()
    if (!Array.isArray(rows)) return nothing(rows)

    const wanted = normalizeName(filer)
    const mine = rows.filter((r) => typeof r.name === "string" && normalizeName(r.name) === wanted)
    if (!mine.length) {
        return nothing({
            status: "no-data",
            reason: `OGE lists no filings under "${filer}".`,
        })
    }

    // Newest first. docDate arrives as "2025-12-31T04:30:29", which sorts
    // correctly as a string, so no date is parsed and no time zone is guessed.
    const filings = mine
        .sort((a, b) => (b.docDate ?? "").localeCompare(a.docDate ?? ""))
        .slice(0, MAX_FILINGS)
        .map((r) => {
            const parsed = parseType(r.type ?? "")
            return {
                label: parsed.label,
                // null on a request-only row: there is nothing to open.
                documentUrl: parsed.documentUrl,
                // false means OGE indexed the filing but published no copy.
                available: parsed.available,
                docDate: r.docDate ?? null,
                agency: r.agency ? decodeEntities(r.agency) : null,
                title: r.title ? decodeEntities(r.title) : null,
                isAmended: Boolean(r.amended),
                // The day the amendment landed. A boolean answers the
                // question the app asks today and quietly throws away a date
                // the government published, so both ride along.
                amendedAt: r.amended || null,
            }
        })

    return NextResponse.json({
        filer,
        source: FEED,
        // Said out loud, the way /api/congress-filings says it, so no client
        // ever has to assume otherwise.
        tradesIncluded: false,
        filings,
        ...OK,
    })
}
